language: go

go:
    - 1.9.6

go_import_path:
    beeme

services:
    - mysql

env:
    - ORM_DRIVER=mysql    ORM_SOURCE="root:@/orm_test?charset=utf8"

install:
    - go get -v $(go list ./...|grep -v vendor/)
    - go get -u github.com/golang/lint/golint

before_script:
    - sh -c "mysql -u root -e 'create database orm_test default charset utf8 COLLATE utf8_general_ci;'"

script:
    - go vet $(go list ./...|grep -v vendor/)
    - sh build.sh
    - go test -v $(go list ./...|grep -v vendor/)
