language: go

go:
    - 1.8.1

go_import_path:
    beeme

services:
    - mysql

env:
    - ORM_DRIVER=mysql    ORM_SOURCE="root:@/orm_test?charset=utf8"

install:
    - go get -v $(go list ./...|grep -v vendor/)
    - go get -u github.com/golang/lint/golint

before_script:
    - sh -c "mysql -u root -e 'create database orm_test;'"

script:
    - for pkg in $(go list ./... | grep -v /vendor/) ; do golint -set_exit_status $pkg ; done
    - go vet $(go list ./...|grep -v vendor/)
    - sh build.sh
    - go test -v $(go list ./...|grep -v vendor/)

after_script:
    - sh -c "mysql -u root -e 'drop database orm_test;'"
